### ISSUE TITLE
Using no AVX instructions

### ISSUE THREAD

**Issue by hahmad2008** [KlugerLab/FIt-SNE#107]
I can't compile the package I got this error:

`!g++  -std=c++11 -O3  src/sptree.cpp src/tsne.cpp src/nbodyfft.cpp  -o bin/fast_tsne -pthread -lfftw3 -lm -Wno-address-of-packed-member
`

it is interrupted and I got the following:

> In file included from src/tsne.cpp:42:0:
> src/annoylib.h:84:17: note: #pragma message: Using no AVX instructions
>  #pragma message "Using no AVX instructions"

Any help please?

**Comment by dkobak** [comment]
Can you post the full output? I think this is not an error but a warning. Should not interrupt the compilation.

**Comment by MeganQiu** [comment]
I also got this warning, but I can use it normally. It won't affect the use if it successfully generates the executor in the bin folder.

**Comment by hahmad2008** [comment]
I am using colab, so where to find the entire log? 

![image](https://user-images.githubusercontent.com/68266028/87430874-7f7ce000-c5ee-11ea-9767-bec95eac95d3.png)

Before that I installed fftw, I extract the package on /tmp folder and install it:
```
path = '/tmp/fftw-3.3.8'

os.chdir(path)

!./configure --enable-threads --enable-openmp --enable-avx 
!make install
```

**Comment by dkobak** [comment]
Sorry, no idea. But I am pretty sure that this message is not an error but a warning.

**Comment by hahmad2008** [comment]
Thank you guys! @MeganQiu & @dkobak  
it is already installed! and this was a warning, I thought it is an error since I got only that message.
