### ISSUE TITLE
Installation error in OSX

### ISSUE THREAD

**Issue by am610** [KlugerLab/FIt-SNE#108]
I install based on the direction given here : 

`$conda config --add channels conda-forge #if not already in your channels. Needed for fftw.
$ conda install cython numpy fftw
$ pip install fitsney`

I get this error : 

`ERROR: Could not find a version that satisfies the requirement fitsney (from versions: none)
ERROR: No matching distribution found for fitsney`

What is this supposed to mean ?

**Comment by linqiaozhi** [comment]
Apologies for delay in responding--but the problem is that the package name should be 'fitsne" not 'fitsney'
