### ISSUE TITLE
Is the PyPI version up to date?

### ISSUE THREAD

**Issue by hyhuang00** [KlugerLab/FIt-SNE#117]
I tried to install FIt-SNE via PyPI using `pip install fitsne` and have successfully ran FIt-SNE algorithm via the function `fitsne.FItSNE`. However, it seems like the PyPI version isn't up to date, as it lacks several new features such as perplexity list, introduced in later versions. Is the PyPI version up to date? If not, could you upload the newest version to PyPI?

**Comment by linqiaozhi** [comment]
Hi @hyhuang00, thanks for the bringing this up. I admit to having neglected the PyPI version, it is definitely out of date--apologies for the inconvenience. I plan to work on it over the weekend. 

If that is not soon enough for you, you can consider using the `fast_tsne.py` Python wrapper in this repository (only disadvantage is that it will first write the input to the hard drive and then read it back), or OpenTSNE.

**Comment by linqiaozhi** [comment]
Hi @hyhuang00, I updated the PyPI version to 1.2.1. Can you try it out and see if the new features you need are working for you?

Thanks!

**Comment by hyhuang00** [comment]
Thank you! I have successfully upgraded and run the function with new features.
