### ISSUE TITLE
Allow to provide initialization

### ISSUE THREAD

**Issue by dkobak** [KlugerLab/FIt-SNE#12]
There is currently no way to provide some particular initialization, despite `TSNE::run()` seemingly supporting this option via `skip_random_init=TRUE`. The relevant code in the `main()` is commented out. It would be great to add this option.

One approach would be to modify the input file format such that if the end of file is not reached when `rand_seed` is read, then the remaining part of the file is taken by the initialization `Y`. This will allow to use the same file format whether one chooses to provide an initialization or not.

(For my own purposes, I have previously modified `bh_tsne` to work like that.)

**Comment by linqiaozhi** [comment]
Yes, providing a particular initialization is not possible with the current input file, but with relatively straightforward modification (that you described) it would be possible. This would be a great feature that would be nice to have.

I'll leave this open until you, or I, or someone else has a chance to implement it and pull request.

**Comment by dkobak** [comment]
OK, I might actually implement it relatively soon.

I was just wondering if there are any legacy issues to be aware of, because clearly much of the code was already written once but then commented out.

**Comment by linqiaozhi** [comment]
This issue is addressed in @dkobak's most recent pull request, which I just merged.

Thanks again!
