### ISSUE TITLE
results file (results_date_seed-.dat) is not created

### ISSUE THREAD

**Issue by gblock173** [KlugerLab/FIt-SNE#123]
Hi,
I tried to use this package, but the results file is not created.  ('results_{date-randomnum}_.dat' file)
Only the 'data_{date-randomnum}_.dat' file is created in my folder. 
Could anyone please let me know what I did wrong? 

here is my error message,

=============== t-SNE v1.2.1 ===============
fast_tsne data_path: data_2022-07-25 17:43:27.482097-31490971.dat
fast_tsne result_path: result_2022-07-25 17:43:27.482097-31490971.dat
fast_tsne nthreads: 128
Read the following parameters:
	 n 81 by d 2445901 dataset, theta 0.500000,
	 perplexity 30.000000, no_dims 2, max_iter 750,
	 stop_lying_iter 250, mom_switch_iter 250,
	 momentum 0.500000, final_momentum 0.800000,
	 learning_rate 200.000000, max_step_norm 5.000000,
	 K -1, sigma -1.000000, nbody_algo 2,
	 knn_algo 1, early_exag_coeff 12.000000,
	 no_momentum_during_exag 0, n_trees 50, search_k 4500,
	 start_late_exag_iter -1, late_exag_coeff -1.000000
	 nterms 3, interval_per_integer 1.000000, min_num_intervals 50, t-dist df 1.000000
Read the 81 x 2445901 data matrix successfully. X[0,0] = 0.950617
Read the initialization successfully.
Perplexity too large for the number of data points!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "{path}/00.Resource/FIt-SNE/fast_tsne.py", line 311, in fast_tsne
    with open(os.getcwd() + '/' + outfile, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '{path}/FIt-SNE/result_2022-07-25 17:43:27.482097-31490971.dat'

**Comment by dkobak** [comment]
> n 81 by d 2445901 dataset

Does your dataset really have only 81 points? And the dimensionality is 2.5 million? Or should it be the other way round?

**Comment by gblock173** [comment]
81 points and 2.4M features are correct. 
It was a sample that I tested before adding more data.
Referring to your answer, I reduced the number of features to about 40,000 and it worked normally. 

thank you :)

**Comment by dkobak** [comment]
This does not make sense to me. The problem was that you cannot use perplexity 30 with fewer than 90 points, and you have only 81. That is what the error message meant:

>  Perplexity too large for the number of data points!

Reducing the number of features won't help that.
