### ISSUE TITLE
Speed issues/questions

### ISSUE THREAD

**Issue by dkobak** [KlugerLab/FIt-SNE#14]
I noticed two issues with speed. I am working with a dataset with n=14k and dimensionality 50.

1. The gradient descent iterations become slower and slower as they progress. This is most pronounced with low perplexities. E.g. with perplexity=10, I get 50 iterations in 0.634327 seconds in the beginning, but it slowly increases to 5-6 seconds per 50 iters towards iteration 1000. Why the slowdown?

   This is less pronounced for larger perplexities. For perpl=100, it grows from 1.3 s to 2-3 s. For perpl=1000, it does not noticeably grow at all (stays at around 9.5 s per 50 iters).

2. For very larger perplexity values (e.g. 1000), the code spends a lot of time after it computes all affinities via Annoy. What I mean is that

```
 Building Annoy tree...
Done building Annoy tree. Begin nearest neighbor search... 
Calculating dynamic kernels using perplexity 
parallel (8 threads):
 - point 0 of 14177, most recent beta calculated is 15.177124 
 - point 10000 of 14177, most recent beta calculated is 35.029297 
```
   this part works in several seconds (maybe 10), but then it takes around 2 minutes until the output continues with 

```
Using the given initialization
Exagerating Ps by 12.000000
Input similarities computed (sparsity = 0.263060)!
Learning embedding...
Using FIt-SNE approximation.
...
```

   This is approximately as much time as is taken by the 1000 gradient descent iterations. What happens during this seeming "pause"? Is the `symmetrizeMatrix()` taking so much time for larger perplexity values?

**Comment by linqiaozhi** [comment]
1. t-SNE is randomly initialized to a very small scale (e.g. 10^-3 by 10^-3), and increases in scale to about 100 by 100 in the typical run. As it increase in scale, it needs more interpolation nodes and subintervals are required to achieve the same accuracy.  Hence, the FFTs at each iteration takes longer and long--particularly after early exaggeration ends. This effect will be especially pronounced if you have few points (like your 14k). The size of the FFT is completely independent of the number of points, and solely determined by the scale of the data.  This [post](https://gauss.math.yale.edu/~gcl22/blog/numerics/low-rank/t-sne/2018/01/11/low-rank-kernels.html) goes into more detail.

I would note that FIt-SNE is still faster than Barnes-Hut for 14k points, but with that few points using Barnes-Hut is also fine. Personally, I find the real utility of FIt-SNE's speed kick in for over ~50k points, and most especially in the hundreds of thousands to millions of points.

2. The number of nearest neighbors computed by FIt-SNE is 3*perplexity. For perplexity 1000, you are computing 3000 nearest neighbors, which is a lot.  You can think of it simply that the P_{ij} matrix is much more dense when each point has 3*1000 neighbors vs. 3*90 neighbors, so everything will be slower (including, perhaps, the symmetrization step--but you'd have to check to make sure it is that).

**Comment by dkobak** [comment]
Thanks.

(1) makes sense. I haven't yet studied how the FFT approximation works; will do!

(2) I understand that everything should be slower, but in fact the Annoy search of 3000 neighbours runs pretty fast. It looks like symmetrization becomes a bottleneck for some reason. I'll try to investigate. (First I'd still need to confirm that it's indeed the symmetrization that takes this time.)

(I guess it's OK to close this if you want. If I find out something more specific about the symmetrization step, we can reopen.)

**Comment by linqiaozhi** [comment]
Okay, thanks--feel free to reopen if you have any more comments!

**Comment by dkobak** [comment]
I can confirm that it is symmetrizing that takes so much time. But I am not going to investigate why this happens now. (I haven't studied the `symmetrizeMatrix()` code.)
