### ISSUE TITLE
Pass on theta

### ISSUE THREAD

**Issue by jspidlen** [KlugerLab/FIt-SNE#17]
Typo in here:

https://github.com/KlugerLab/FIt-SNE/blob/9f17132b1edb412ee63b2305f8615c95f246dbe0/fast_tsne.R#L59

Should be 
writeBin( as.numeric(theta), f,size= 8) #theta
I think. 

Tried to fix via a pull request, but got a permission denied.

Josef

**Comment by linqiaozhi** [comment]
Hey Josef,

Thanks for the issue report, you are absolutely right about this bug.

Did you make a fork, commit your changes to that fork, and then pull request? I don't see the fork among your repos. Please let me know where you are getting an error--it should definitely be possible to do a pull request, just merged one yesterday. 

GCL

**Comment by dkobak** [comment]
@jspidlen I fixed this here: https://github.com/KlugerLab/FIt-SNE/pull/18.
