### ISSUE TITLE
Report KL divergence during optimization

### ISSUE THREAD

**Issue by pavlin-policar** [KlugerLab/FIt-SNE#21]
It would be really convenient if the optimization reported on the current KL divergence (or at least the final one), like scikit-learn or Multicore tSNE does. This could then be used later on for e.g. automatically determining perplexity (Cao, Wang 2017).

Implementing this should be trivial. We would need to add a logging for the error and then to actually compute the KL divergence, we'd need to add a few returns to the gradient code.

To make things convenient for the implementation, we can rewrite the KL divergence as

![image](https://user-images.githubusercontent.com/5758119/42136961-95a50986-7d64-11e8-9b2b-9521a5a6e57e.png)

where `\hat{q_{ij}}` denotes the unnormalized `q_{ij}`s. This is exactly what scikit-learn does (and multicore tSNE if I remember correctly), so their code can be used as a reference if needed.

This is really easy to compute with the current implementation, because we can compute the first term during the main gradient loop, and if we keep a `sum_P` variable and return `sum_Q` from the negative gradient methods, we can easily compute the second term as well. Literally, everything is already in place for this to be implemented, a couple returns need to be added, and the actual expression written into code. 

Note that during the early (and late) exaggeration phases the error will be incorrect, because we *P* will be scaled, but it is also really easy to work out a correction for this:

![image](https://user-images.githubusercontent.com/5758119/42136972-b416f55a-7d64-11e8-81d8-11f8142b4adb.png)

where the first term would be the KL divergence that we compute during optimization and the second term is the correction.

I can look into it when time permits unless somebody beats me to it :)

**Comment by linqiaozhi** [comment]
Thanks for bringing this up, @pavlin-policar! The KL divergence is now reported every 50 iterations, as of #32.
