### ISSUE TITLE
Lots of debugging files are created when using exact t-SNE

### ISSUE THREAD

**Issue by dkobak** [KlugerLab/FIt-SNE#26]
I noticed that when exact t-SNE is used (theta=0), the code creates a lot of debugging files in the temp/ folder. This is not the most pressing issue of course, but I was a bit confused to see 1000 files like `exact_gradient0.txt` in the `temp/` when running the exact t-SNE.

This happens in `computeExactGradient` which was modified compared to the `bhtsne` to do exactly this. There is also `computeExactGradientTest` which also creates some similar (but not identical) files. However, `computeExactGradientTest` is never run because `bool measure_accuracy = false;` globally.

I assume that `computeExactGradientTest` is some debugging function which is OK but I am wondering if the non-debugging version `computeExactGradient` can be reverted back to the `bhtsne` state without any files created in temp/.

If the answer is yes, then should the `computeExactGradientTest` be changed to save all the stuff that `computeExactGradient` is now saving?

Or maybe `computeExactGradient` can be modified to do the logging only if `measure_accuracy` is set to true?

**Comment by linqiaozhi** [comment]
Yes, these are vestiges of when I was doing diagnostics and testing accuracy of the interpolation scheme. I think after #20, computeExactGradient() no longer outputs any files? Does that resolve this issue?

Thanks for catching this!

**Comment by dkobak** [comment]
I think we can further delete lines https://github.com/KlugerLab/FIt-SNE/blob/master/src/tsne.cpp#L843 843-845 and 853-855. I will do it in my next PR.

**Comment by dkobak** [comment]
This is done now.
