### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by MayukhSobo** [KlugerLab/FIt-SNE#27]
I am getting the error. Please help
```
Traceback (most recent call last):
  File "data.py", line 27, in <module>
    X_embed = fast_tsne(X_tfidf.toarray())
  File "/Users/mayukh-imac/Documents/ML/FIt-SNE/fast_tsne.py", line 71, in fast_tsne
    f.write(X.tobytes())
OSError: [Errno 22] Invalid argument
```

**Comment by linqiaozhi** [comment]
If you are using Python, I'd strongly suggest you use the FIt-SNE PyPI package available [here](https://pypi.python.org/pypi/fitsne). The fast_tsne.py in this repo is only for testing purposes--not for actual use. 

In fact, I see now that `fast_tsne.py` does not work for me unless I change the line 79 to 

`subprocess.call(os.getcwd()+'/bin/fast_tsne')`

So, I will have to fix that. 

If you'd prefer to use this wrapper, then we need to figure out what is preventing you from writing to disk at that step. Could it be that your current working directory is not the FIt-SNE folder?

**Comment by dkobak** [comment]
@linqiaozhi I'm using `fast_tsne.py` and it works very well for me. As it's written, it supposes that `fast_tsne.py` and `fast_tsne` binary are both located in the same folder where the Python script is. This can be changed, but so far I found this to be the most practical.

In other words, currently I manually copy `fast_tsne.py` and `fast_tsne` binary into my current folder with scripts. Then I do `import fast_tsne` etc. I can provide an example Python notebook for the examples folder.

If we want to change the directories, then I'm not quite sure what a better arrangement be.

**Comment by dkobak** [comment]
@MayukhSobo As is written in `fast_tsne.py`,

`# It assumes that fast_tsne.py and fast_tsne binary are both in the working directory`

is this true for you?

**Comment by dkobak** [comment]
@MayukhSobo Have you solved this problem?

**Comment by MayukhSobo** [comment]
Sorry @dkobak I didn't try it further. I had a timeline to follow so could not invest much time in this.

**Comment by linqiaozhi** [comment]
> @MayukhSobo As is written in `fast_tsne.py`,
> 
> `# It assumes that fast_tsne.py and fast_tsne binary are both in the working directory`
> 
> is this true for you?

Hey @dkobak, is this issue is now resolved? I think you have made changes to `fast_tsne.py` such that it does not need to be in the same folder as the executables in this issue was opened. In particular, that comment is no longer in the wrapper file. Can we close?

**Comment by dkobak** [comment]
@linqiaozhi Yes, I think this issue is obsolete and can be closed.
