### ISSUE TITLE
Higher dimensional embeddings

### ISSUE THREAD

**Issue by lmcinnes** [KlugerLab/FIt-SNE#34]
First, thanks for the great package, and for making it easy to use! I am interested in embedding into three dimensions or higher. I'm using the python API from the latest version of PyPI (0.2.5) and it appears to support this via the ``no_dims`` parameter. The resulting array is of the correct shape (as specified by the value of ``no_dims``), but the results appear to be essentially random when visualized (either in 2D slices, or in 3D). I couldn't find any documentation on this, and was hoping you could clarify the parameter/usage for embedding into higher dimensional spaces. Thanks in advance.

**Comment by linqiaozhi** [comment]
Hi Leland, thanks for trying out FIt-SNE! While our interpolation approach can be extended to embedding in higher dimensions (at the cost of using more interpolation points), dimensions >2 have not been implemented. In other words, the `no_dims` parameter can only take 1 or 2. 

You are absolutely right that this is not clear in the documentation, and in the next update to the python package I will change it to give an error if any number other than 1 or 2 are passed in. Thanks for finding this...it can be confusing to people.

**Comment by dkobak** [comment]
I can do it for the python wrapper that I provided. Not sure about the other python interface.

**Comment by lmcinnes** [comment]
Thanks for clarifying. Do you have any idea how the Fourier interpolation
will scale with embedding dimension? The space tree approach in Barnes-Hut
scales exponentially, but I thought your approach may perhaps be slightly
more efficient?

**Comment by linqiaozhi** [comment]
Our approach is O(N), but the constant scales exponentially in embedding dimension. For 3-dimensional, there are Fast Multipole Methods that would work well here, but for even higher dimensions a different approach entirely would probably be required. 

Most applications we are aware of for t-SNE are 2-dimensional, so we did not try 3-dimensional or higher...so I'm afraid I don't have any actual benchmarks I could share.

**Comment by dkobak** [comment]
@linqiaozhi I thought, maybe it's easier to add a check to the C++ code and let it exit with an error if `no_dims>2` for the FFT method. Can Barnes-Hut handle any no_dims?

**Comment by lmcinnes** [comment]
Thanks George; I agree that for most t-SNE use cases 3 dimensions at most
are likely sufficient, and it sounds like you could get that far at least.
I appreciate the work to get it this fast in 2 dimensions!

**Comment by linqiaozhi** [comment]
@dkobak I agree, adding a check to the C++ code would be best. And yes, BH can handle any no_dims.

@lmcinnes Thanks again for letting us know about this issue!
