### ISSUE TITLE
Error: Invalid knn_algo param

### ISSUE THREAD

**Issue by cartal** [KlugerLab/FIt-SNE#50]
Hi,

I'm trying to use FIt-SNE within Seurat and I'm following the instructions they provide. 

The first issue is that the github FIt-SNE fails to compile, and it complains about the following error:

`src/parallel_for.h:29:37: error: ‘bind’ is not a member of ‘std’`

I solved this by including `#include <functional>`, and then it was possible to compile. And the binary seems to work as expected. However, when I try to run it as per Seurat, I've got the following error:

`Invalid knn_algo param
Error in fftRtsne(X = as.matrix(x = data.use), dims = dim.embed, rand_seed = seed.use,  : 
  tsne call failed` 

I have run several datasets and I always get the same error. Any ideas?

**Comment by linqiaozhi** [comment]
Hey @cartal, thanks for the issue report. 

> Hi,
> 
> I'm trying to use FIt-SNE within Seurat and I'm following the instructions they provide.
> 
> The first issue is that the github FIt-SNE fails to compile, and it complains about the following error:
> 
> `src/parallel_for.h:29:37: error: ‘bind’ is not a member of ‘std’`
> 
> I solved this by including `#include <functional>`, and then it was possible to compile. And the binary seems to work as expected. 

Yes, this was a problem we encountered before, but I think when we made recent changes we removed that line. Will have to add it back in as soon as we can.

> However, when I try to run it as per Seurat, I've got the following error:
> 
> `Invalid knn_algo param Error in fftRtsne(X = as.matrix(x = data.use), dims = dim.embed, rand_seed = seed.use, : tsne call failed`
> 
> I have run several datasets and I always get the same error. Any ideas?

Are you passing any parameters to the function? Do you have a small example I could try and run? I'm wondering if recent changes made it somehow incompatible with the Seurat wrapper, but looking [here](https://github.com/satijalab/seurat/blob/7618ac8798e2aefc509529f07af9d2836b96a1be/R/dimensional_reduction.R#L312) it does not seem like they use any parameters that changes (or any parameters, really).

**Comment by johan-gson** [comment]
I'm having the same problem. This is caused by the adding of 4 extra parameters in the data file (i.e. a change in the interface), commit 1a2a3b8e57e061e605909705825602c0f542e244. The wrapper in Seurat needs to be updated, I don't think there is an error in FIt-sne. The issue exists in Seurat as well, see https://github.com/satijalab/seurat/issues/904 , and there is a workaround mentioned there until they fix it.
I would guess this issue can be closed.

**Comment by dkobak** [comment]
@johan-gson Thanks.

@linqiaozhi We (you?) could probably directly PR a fix to `seurat`: here is their function and it should be an easy fix to make it work with the v1.0.0 binary https://github.com/satijalab/seurat/blob/master/R/dimensional_reduction_internal.R#L327.

**Comment by linqiaozhi** [comment]
It appears this is now [fixed](https://github.com/satijalab/seurat/issues/1030#issuecomment-451093628) in Seurat 3.0. Please re-open if there are further problems.
