### ISSUE TITLE
Missing nthreads parameter in python wrapper

### ISSUE THREAD

**Issue by pavlin-policar** [KlugerLab/FIt-SNE#61]
I've been looking at the python wrapper `fast_tsne.py` and as far as I can tell, there's no way to specify the number of threads. Looking at the code, it's also not clear to me how to implement this. 

I am aware of [pyFIt-SNE](https://github.com/KlugerLab/pyFIt-SNE/tree/master/fitsne), where I can specify the number of threads, but it doesn't have the nice perplexity list that Dmitry implemented.

**Comment by dkobak** [comment]
That's right. I will implement it. I think it's supposed to be passed to the binary executable not via the .dat file but as a command line parameter. Should be an easy fix.

**Comment by linqiaozhi** [comment]
Resolved by @dkobak as one of the fixes in 01e181e787eae4c32b25a9dea531075227258333.
