### ISSUE TITLE
Interpolation times fluctuating

### ISSUE THREAD

**Issue by dkobak** [KlugerLab/FIt-SNE#67]
When running MNIST with df=.5, lr=1000, max_iter=10000, I noticed that the interpolation times go fluctuate quite wildly:

```Iteration 8850 (50 iterations in 96.77 seconds), cost 3.636429
Iteration 8900 (50 iterations in 156.69 seconds), cost 3.635826
Iteration 8950 (50 iterations in 144.49 seconds), cost 3.633185
Iteration 9000 (50 iterations in 167.69 seconds), cost 3.634107
Iteration 9050 (50 iterations in 216.43 seconds), cost 3.632257
Iteration 9100 (50 iterations in 98.15 seconds), cost 3.632917
Iteration 9150 (50 iterations in 87.34 seconds), cost 3.630620
Iteration 9200 (50 iterations in 115.28 seconds), cost 3.629794
Iteration 9250 (50 iterations in 213.32 seconds), cost 3.631249
```

This does not happen early in the optimization. The runtime grows exactly monotonically until it reaches about 10 seconds per 50 iterations (somewhere around iteration=1200). After that it begins to fluctuate and does it more and more so.

Any idea why this might be happening?

**Comment by linqiaozhi** [comment]
This is my first thought: the number of interpolation nodes does not grow smoothly with the size of the embedding, rather there is a grid of allowed numbers of nodes:

https://github.com/KlugerLab/FIt-SNE/blob/d007435c451c488d2e3c4eb3a81aa2c996a8f383/src/tsne.cpp#L903-L906

Perhaps it is bouncing around between those grid points, and getting slower/faster accordingly. The way to diagnose it would be to check the number of nodes/embedding-size at each iteration and see if it is bouncing around.

**Comment by linqiaozhi** [comment]
I'm wondering now if this could maybe be due to the overshooting phenomenon that we discussed in #93? It was this kind of variation in runtimes that tipped us off to it in the first place. I guess the question is whether the embedding size was much larger between iterations 9200-9250 than it was for 9050-9100.

**Comment by dkobak** [comment]
I don't know. I haven't seen this occurring since then, but I haven't used 10000 iter either. To be honest, this was such an edge case that I don't feel motivated to explore this further. I suggest to close this issue. If it ever appears again, we can get back to it.
