### ISSUE TITLE
CMake configuration is hard coded

### ISSUE THREAD

**Issue by rajarshi** [KlugerLab/FIt-SNE#69]
Hi, I am trying to explore the tool for embedding large datasets (300K observations, 1024 dimensions). I checked out the code, and modified the Makefile to remove hardcoded paths to the developers home directory. However, afetr that cmake reports an error
```
(general) ✘-255 ~/src/FIt-SNE [master|✚ 1] 
11:03 $ make
CMake Error: The source directory "/Users/guha/src/FIt-SNE" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```
Do you know hwo this could be fixed?

**Comment by linqiaozhi** [comment]
Hi @rajarshi, CMake was temporarily introduced in #20, but we decided in that thread to not use CMake, and removed the files corresponding to it. However, it looks like we neglected to remove the Makefile itself! We need to remove that, as it is very confusing!

Instead, you should compile with the following command, as per the readme:

`g++ -std=c++11 -O3  src/sptree.cpp src/tsne.cpp src/nbodyfft.cpp  -o bin/fast_tsne -pthread -lfftw3 -lm`

**Comment by linqiaozhi** [comment]
Okay, removed the Makefile to avoid confusion. Please re-open if you have trouble compiling using the instructions in the readme. 

Thanks for using FIt-SNE!
