### ISSUE TITLE
is it possible to use this with a distance matrix input?

### ISSUE THREAD

**Issue by sg-s** [KlugerLab/FIt-SNE#71]
Can I only provide a NxN matrix of pairwise distances, as in van der Maaten's `tsne_d` ?

**Comment by linqiaozhi** [comment]
An old branch supports this feature, and it would be great to implement for this new version. Please see https://github.com/KlugerLab/FIt-SNE/issues/62#issuecomment-453630634.

**Comment by sg-s** [comment]
thanks, will look there!

**Comment by young-stack** [comment]
> Can I only provide a NxN matrix of pairwise distances, as in van der Maaten's `tsne_d` ?

if you want using other distance metrics method, you can compute row_P, col_P, and var_P by yourself and set opts.load_affinities as load.

**Comment by sg-s** [comment]
> > Can I only provide a NxN matrix of pairwise distances, as in van der Maaten's `tsne_d` ?
> 
> if you want using other distance metrics method, you can compute row_P, col_P, and var_P by yourself and set opts.load_affinities as load.

No, I have a precomputed distance matrix that I want to use.
