### ISSUE TITLE
No multithreading after running RunTSNE with "test.method="FIt-SNE", nthreads = 8"

### ISSUE THREAD

**Issue by kaizen89** [KlugerLab/FIt-SNE#80]
Hi,
I am using seurat v3 and FIt-SNE v1.1.0 but it seems that only one thread is used when running fron Seurat: 
```
seurat_object <- RunTSNE(seurat_object, dims = 1:40, test.method="FIt-SNE", nthreads = 4)
```
Here is a reproducible example
```
library(Seurat)
download.file("https://www.dropbox.com/s/63gnlw45jf7cje8/pbmc3k_final.rds?dl=1", "~/Downloads/pbmc3k_final.rds")
pbmc <- readRDS(file = "~/Downloads/pbmc3k_final.rds")
pbmc <- RunTSNE(pbmc, dims = 1:40, test.method="FIt-SNE", nthreads = 4)
```
Any help?
Thanks

**Comment by dkobak** [comment]
@kaizen89 Why did you close this?

**Comment by kaizen89** [comment]
Turns out I made a mistake, it should be "tsne.method" and not "test.method". It was running t-SNE by default without any error, but that is related to Seurat.
