### ISSUE TITLE
annoylib does not compile using g++ 9

### ISSUE THREAD

**Issue by dkobak** [KlugerLab/FIt-SNE#81]
Just tried installing FIt-SNE on a new laptop with a fresh Ubuntu installation, and the compilation failed with some errors in `annoylib`. Googling led to this issues: https://github.com/spotify/annoy/issues/310. Downloading the current `annoylib.h` fixed the problem. Are you OK with updating the version of Annoy included in FIt-SNE to the latest one? Then I can do a PR.

**Comment by linqiaozhi** [comment]
Great catch--yes, please.

**Comment by dkobak** [comment]
Oops -- I accidentally pushed it right here. It should be fine, but please check that everything is okay. I also heavily updated the Python demo notebook.

**Comment by dkobak** [comment]
I mark this as closed now but please confirm that everything works fine when you have a chance.
