### ISSUE TITLE
Annoy warnings

### ISSUE THREAD

**Issue by dkobak** [KlugerLab/FIt-SNE#85]
I suggest we add `-Wno-address-of-packed-member` to the `gcc` command in the README. At least for me, it suppresses several screens of warnings. See here: https://github.com/spotify/annoy/issues/310#issuecomment-569546281

**Comment by linqiaozhi** [comment]
I just tried the current g++ call on my Ubuntu machine and on OS X. I did not get any warnings. But I do recall on other machines getting lots of warnings.

I'm sure this is very compiler dependent, though. Which compiler/OS are you using?

**Comment by dkobak** [comment]
The warnings only appeared after I upgraded Ubuntu to 19.10. Now `gcc --version` outputs 9.2.1. I think the warnings stated to appear in gcc 9.

**Comment by linqiaozhi** [comment]
Added to the README. Thanks Dmitry!
