### ISSUE TITLE
Default start_late_exag_iter

### ISSUE THREAD

**Issue by dkobak** [KlugerLab/FIt-SNE#90]
Whenever I use non-default `late_exag_coeff`, I set `start_late_exag_iter=250`, so that it starts right after the early exaggeration. I suggest to make it default behaviour in the wrappers, so that one only needs to specify start_late_exag_iter.

AFAIK openTSNE does it by default. The parameter is called `exaggeration` and its description is "The exaggeration factor to use during the normal optimization phase." (https://opentsne.readthedocs.io/en/latest/api/index.html)

**Comment by linqiaozhi** [comment]
Resolved in #93
