### ISSUE TITLE
Conda package / new release?

### ISSUE THREAD

**Issue by raivivek** [KlugerLab/FIt-SNE#91]
Hi, I'm wondering if you'd be interested in vendoring this package through Conda? I can help with that if needed.

Also, it appears that there have been many commits post last release. It'd be nice to create a new release to reflect newest changes. Thanks!

**Comment by raivivek** [comment]
WIP for Conda package here: https://github.com/conda-forge/staged-recipes/pull/10932

**Comment by dkobak** [comment]
But FIt-SNE depends on FFTW, wouldn't it be a problem?

**Comment by dkobak** [comment]
> Also, it appears that there have been many commits post last release. It'd be nice to create a new release to reflect newest changes. Thanks!

We are planning to push some changes to the default parameters and will release a new version after that. Might take a week or so.

**Comment by raivivek** [comment]
@dkobak Conda package for FFTW already exist, so it should not be a problem. As you can see from the conda-forge link above, the build seems to be successful.

**Comment by linqiaozhi** [comment]
@raivivek Thanks for working on this! Distributing through Conda sounds pretty great. What else needs to be done?

Also, pardon my ignorance, but how would it then be updated when we make changes on this repository? Would someone have to then copy those new changes to the Conda recipe?  Or will it some how automatically be updated when we make new releases?

Also, @dkobak is absolutely right, we will be making a new release as soon as we change the defaults in the wrappers.

**Comment by raivivek** [comment]
Hi @linqiaozhi -- The package is now merged in Conda and already available
so I don't need anything at the moment.


As for upgrade, it actually pretty painless. As long as you create new
tagged releases, GitHub bots will automatically create new recipes and
update the distribution. If nothing wrt how the package is compiled has
changed or any dependencies, no extra work has to be done. Otherwise I will
have to update it manually.

**Comment by pavlin-policar** [comment]
@raivivek This is a great idea, however, looking at the conda-forge page (https://anaconda.org/conda-forge/fit-sne) and the feedstock (https://github.com/conda-forge/fit-sne-feedstock), the windows package is not being packaged, meaning that conda can't be used to install FIt-SNE on Windows. That's almost certainly something you want to do. You probably also want to add George or Dmitry as recipe maintainers, so they can quickly update any new releases so they're present on conda as well.

@linqiaozhi, @dkobak I'm not sure how the updating procedure goes on conda if it's not a PyPi package. With openTSNE, which is on PyPi, I'll usually just have to merge a PR that the conda bot automatically opens when I push a new release to PyPi. I don't know how to do this if it's tied directly to the github repository. Maybe @raivivek can explain a bit more?

**Comment by raivivek** [comment]
@pavlin-policar I could certainly use help on getting the Windows build to work. I did not have enough time/familiarity with the tool to debug the issue properly -- so something better than nothing. If authors here can update the recipe with Windows build, then we can also include their names in recipe maintainers.

As for your second question, I believe it works the same way the PyPi work. It is tied directly to the github repository, so if a new tagged released is created, the bot will open a new pull request automatically.

**Comment by raivivek** [comment]
https://github.com/conda-forge/fit-sne-feedstock

This would be the appropriate repository to update the recipe. @linqiaozhi @dkobak

**Comment by dkobak** [comment]
@raivivek George made a new release yesterday. Let's see if it magically appears on conda :)

**Comment by raivivek** [comment]
@dkobak Here it is -- https://github.com/conda-forge/fit-sne-feedstock/pull/1 It's almost magical except that someone has to review and approve it :) So if you'd like I can add you as maintainer.

**Comment by dkobak** [comment]
Thanks! Please also add @linqiaozhi then.

**Comment by raivivek** [comment]
Will do in next update. Thanks!
