### ISSUE TITLE
Windows executable for Version 1.2.0 not compiling

### ISSUE THREAD

**Issue by linqiaozhi** [KlugerLab/FIt-SNE#95]
Since @jspidlen contributed a Visual Studio solution in #23, I have been using it to compile a Windows binary that I attach to each release. With this Version 1.2.0 release, I am encountering errors related to the Annoy library...even though we have not made any changes to the Annoy library since the last release. 

The first error is the file mman.h is not in the include path. That file is in src\winlibs, and when I add it to the Additional Include Paths, a whole new series of errors appear relating to other dependencies of Annoy. I have no experience with Visual Studio, so I am struggling to solve them...just wanted to reach out to @jspidlen or other Windows developers to see if you could figure out what changed.

**Comment by dkobak** [comment]
Oh this might be why the conda package complained about the Windows version!

Will @JosefFlowJo get notified or should we email him?

**Comment by JosefFlowJo** [comment]
Thanks Dmitry,
My apologies, I don’t have the computer with the MS Visual Studio that I had back in 2018 for this, so I don’t think I will be able to help troubleshoot the Windows builds at this point.
Josef

**Comment by dkobak** [comment]
@linqiaozhi We did update the Annoy version though, around four months ago: https://github.com/KlugerLab/FIt-SNE/commit/42e46177d6f3f86981dbc6faf9e517104cbad7d4. I wonder if the errors are connected to that.

> The first error is the file mman.h is not in the include path. That file is in src\winlibs, and when I add it to the Additional Include Paths, a whole new series of errors appear relating to other dependencies of Annoy.

I would guess that `src\winlibs` should be in the include path (didn't you need it there previously?). Can you post the errors you are getting?

**Comment by dkobak** [comment]
Hmm, we might need to update the mman.h file, taking it from here: https://github.com/spotify/annoy/tree/master/src

**Comment by linqiaozhi** [comment]
Resolved!
